### ISSUE TITLE
TypeError: No context on context stack

### ISSUE THREAD

**Issue by stelehm** [junpenglao/Bayesian-Cognitive-Modeling-in-Pymc3#2]
Hello.

I was trying to run the first code-example, but couldn't reproduce the first model and traceplot.
I only get the following output.
![image](https://user-images.githubusercontent.com/5700597/29604955-77e19fac-87e9-11e7-8407-855226976013.png)

Taking a look into the console, I found following error-message:

Traceback (most recent call last):
  File "C:\FILES\Python\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\FILES\Python\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\FILES\Python\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\FILES\Python\lib\site-packages\joblib\pool.py", line 362, in get
    return recv()
  File "C:\FILES\Python\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "C:\FILES\Python\lib\site-packages\pymc3\step_methods\arraystep.py", line 38, in __new__
    model = modelcontext(kwargs.get('model'))
  File "C:\FILES\Python\lib\site-packages\pymc3\model.py", line 131, in modelcontext
    return Model.get_context()
  File "C:\FILES\Python\lib\site-packages\pymc3\model.py", line 123, in get_context
    raise TypeError("No context on context stack")
TypeError: No context on context stack

**Comment by junpenglao** [comment]
hmm that's quite weird. Are you using GPU on Theano? 
Could you try update PyMC3 to master?
